//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApplication1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _006cd6af8c93c7d2686a2615d5b37b46_scissors_clip_art_cartoon_cartoon_scissors_clipart_216_160 {
            get {
                object obj = ResourceManager.GetObject("006cd6af8c93c7d2686a2615d5b37b46_scissors-clip-art-cartoon-cartoon-scissors-clipa" +
                        "rt_216-160", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _006cd6af8c93c7d2686a2615d5b37b46_scissors_clip_art_cartoon_cartoon_scissors_clipart_216_1601 {
            get {
                object obj = ResourceManager.GetObject("006cd6af8c93c7d2686a2615d5b37b46_scissors-clip-art-cartoon-cartoon-scissors-clipa" +
                        "rt_216-1601", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _55f5b7cf59b9ecdb1710c1f576a0eb4c_boulder_illustration_of_a_cartoon_rocks_clipart_1300_977 {
            get {
                object obj = ResourceManager.GetObject("55f5b7cf59b9ecdb1710c1f576a0eb4c_boulder-illustration-of-a-cartoon-rocks-clipart_" +
                        "1300-977", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _55f5b7cf59b9ecdb1710c1f576a0eb4c_boulder_illustration_of_a_cartoon_rocks_clipart_1300_9771 {
            get {
                object obj = ResourceManager.GetObject("55f5b7cf59b9ecdb1710c1f576a0eb4c_boulder-illustration-of-a-cartoon-rocks-clipart_" +
                        "1300-9771", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gray_floor_texture_wallpaper_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("gray_floor_texture-wallpaper-1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toonvectors_10157_d {
            get {
                object obj = ResourceManager.GetObject("toonvectors-10157-d", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
